<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DemoScene.xml" />
    <None Remove="DemoLevel.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DemoScene.xml" />
    <EmbeddedResource Include="DemoLevel.xml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="libs/**" />
    <Compile Remove="libs\**" />
    <EmbeddedResource Remove="libs\**" />
    <None Remove="libs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="libs\V12.Basic\V12.Basic.csproj" />
    <ProjectReference Include="libs\V12.Pak\V12.Pak.csproj" />
  </ItemGroup>

</Project>
